### PR TITLE
Improve USBProxy reliability

### PR DESCRIPTION
**Pull request by antoinevg**
This PR fixes a few things:

* Refactor `clear_feature_endpoint_halt` arguments in the USB HAL driver to match stall arguments.
* Add a `clear_feature_endpoint_halt` verb to the Moondancer GCP class.
* Compiler warnings on the latest rustc release.
* Incorrect reference to a Makefile target.
* Fixes a compiler error when ladybug is enabled.

Depends on: https://github.com/greatscottgadgets/facedancer/pull/106

### CODE REVIEW

**Comment by mossmann** [comment]
I'm seeing `rubber-ducky.py` fail with this:
```
INFO    | moondancer     | Using the Moondancer backend.
INFO    | moondancer     | Connected FULL speed device 'facedancer.devices.keyboard.USBKeyboardDevice' to target host.
INFO    | rubber-ducky   | Beginning message typing demo...
INFO    | moondancer     | Disconnecting from target host.
Traceback (most recent call last):
  File "/tmp/./rubber-ducky.py", line 25, in <module>
    main(device, type_letters())
  File "/tmp/f/lib/python3.11/site-packages/facedancer/devices/__init__.py", line 41, in default_main
    device.emulate(*coroutines)
  File "/tmp/f/lib/python3.11/site-packages/facedancer/device.py", line 232, in emulate
    self.run_with(*coroutines)
  File "/tmp/f/lib/python3.11/site-packages/facedancer/device.py", line 217, in run_with
    asyncio.run(inner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/f/lib/python3.11/site-packages/facedancer/device.py", line 215, in inner
    await asyncio.gather(self.run(), *coroutines)
  File "/tmp/f/lib/python3.11/site-packages/facedancer/device.py", line 204, in run
    self.backend.service_irqs()
  File "/tmp/f/lib/python3.11/site-packages/facedancer/backends/moondancer.py", line 398, in service_irqs
    events: List[Tuple[int, int]] = self.api.get_interrupt_events()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/f/lib/python3.11/site-packages/pygreat/comms.py", line 1126, in method
    return self.execute_command(verb_number, in_format, out_format, name=name, class_name=class_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/f/lib/python3.11/site-packages/pygreat/comms.py", line 1281, in execute_command
    return self.comms_backend.execute_command(self.CLASS_NUMBER, verb, in_format,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/f/lib/python3.11/site-packages/pygreat/comms.py", line 788, in execute_command
    raw_result = self.execute_raw_command(class_number, verb, payload, timeout,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/f/lib/python3.11/site-packages/pygreat/comms_backends/usb1.py", line 403, in execute_raw_command
    self.device_handle.controlWrite(usb1.TYPE_VENDOR | usb1.RECIPIENT_DEVICE,
  File "/home/mossmann/.local/lib/python3.11/site-packages/usb1/__init__.py", line 1349, in controlWrite
    return self._controlTransfer(request_type, request, value, index, data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mossmann/.local/lib/python3.11/site-packages/usb1/__init__.py", line 1326, in _controlTransfer
    mayRaiseUSBError(result)
  File "/home/mossmann/.local/lib/python3.11/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/mossmann/.local/lib/python3.11/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorTimeout: LIBUSB_ERROR_TIMEOUT [-7]
```

**Comment by antoinevg** [comment]
I thought this might have been because of the other subtle ZLP I caught in https://github.com/greatscottgadgets/cynthion/pull/183 but both branches are working fine for me?

I see it died during a libgreat RPC call, it could maybe be that the firmware had crashed or gotten in a weird state?

Can you replicate it again if you do a fresh firmware build&boot?

**Comment by antoinevg** [comment]
Another thought occurred to me last night, did you also update your Facedancer to: https://github.com/greatscottgadgets/facedancer/pull/106

**Comment by mossmann** [comment]
> Another thought occurred to me last night, did you also update your Facedancer to: [greatscottgadgets/facedancer#106](https://github.com/greatscottgadgets/facedancer/pull/106)

No. Should I? I test everything with released versions of dependencies. If a different version of a dependency is required, that should be specified in the PR.

**Comment by antoinevg** [comment]
> No. Should I? I test everything with released versions of dependencies. If a different version of a dependency is required, that should be specified in the PR.

That would explain it then. 😂

The real question though is how did I manage to forget to add any details to the PR description? 🙈

**Comment by KeuntaeShin** [comment]
I'm also facing this issue exactly same. Any update?

**Comment by antoinevg** [comment]
Can you please try updating your cynthion & facedancer installs to the latest version and let us know if the problem still occurs:

```
pip install --upgrade cynthion
cynthion update

pip install --upgrade facedancer
```

**Comment by KeuntaeShin** [comment]
@antoinevg , Failed


`cynthion run facedancer
Updating SoC firmware flash with 55900 bytes...
Operation complete!
Uploading target bitstream to FPGA with 441927 bytes...
Operation complete!
`

`cynthion info 
Cynthion version: 0.1.6
Apollo version: 1.1.0
Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]

Found Apollo stub interface!
	Bitstream: Facedancer (Cynthion Project)
	Vendor ID: 1d50
	Product ID: 615b
	bcdDevice: 0104
	Bitstream serial number: 398162cba3ac60de

For additional device information use the --force-offline option.
`

`
python ./rubber-ducky.py 
INFO    | moondancer     | Using the Moondancer backend.
INFO    | moondancer     | Connected FULL speed device 'facedancer.devices.keyboard.USBKeyboardDevice' to target host.
INFO    | rubber-ducky   | Beginning message typing demo...
INFO    | moondancer     | Disconnecting from target host.
Traceback (most recent call last):
  File "/facedancer/examples/./rubber-ducky.py", line 25, in <module>
    main(device, type_letters())
  File "/lib/python3.10/site-packages/facedancer/devices/__init__.py", line 41, in default_main
    device.emulate(*coroutines)
  File "/lib/python3.10/site-packages/facedancer/device.py", line 228, in emulate
    self.run_with(*coroutines)
  File "/lib/python3.10/site-packages/facedancer/device.py", line 213, in run_with
    asyncio.run(inner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/lib/python3.10/site-packages/facedancer/device.py", line 211, in inner
    await asyncio.gather(self.run(), *coroutines)
  File "/lib/python3.10/site-packages/facedancer/device.py", line 200, in run
    self.backend.service_irqs()
  File "/lib/python3.10/site-packages/facedancer/backends/moondancer.py", line 427, in service_irqs
    events: List[Tuple[int, int]] = self.api.get_interrupt_events()
  File "/lib/python3.10/site-packages/pygreat/comms.py", line 1126, in method
    return self.execute_command(verb_number, in_format, out_format, name=name, class_name=class_name,
  File "/lib/python3.10/site-packages/pygreat/comms.py", line 1281, in execute_command
    return self.comms_backend.execute_command(self.CLASS_NUMBER, verb, in_format,
  File "/lib/python3.10/site-packages/pygreat/comms.py", line 788, in execute_command
    raw_result = self.execute_raw_command(class_number, verb, payload, timeout,
  File "/lib/python3.10/site-packages/pygreat/comms_backends/usb1.py", line 403, in execute_raw_command
    self.device_handle.controlWrite(usb1.TYPE_VENDOR | usb1.RECIPIENT_DEVICE,
  File "/lib/python3.10/site-packages/usb1/__init__.py", line 1330, in controlWrite
    return self._controlTransfer(request_type, request, value, index, data,
  File "/lib/python3.10/site-packages/usb1/__init__.py", line 1307, in _controlTransfer
    mayRaiseUSBError(result)
  File "/lib/python3.10/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/lib/python3.10/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorTimeout: LIBUSB_ERROR_TIMEOUT [-7]
`

**Comment by KeuntaeShin** [comment]
@antoinevg , There was only on chance after reboot:

> cynthion run facedancer
> Updating SoC firmware flash with 55900 bytes...
> Operation complete!
> Uploading target bitstream to FPGA with 441927 bytes...
> Operation complete!
> 
> sudo python rubber-ducky.py
> --
> INFO    | moondancer     | Using the Moondancer backend.
> INFO    | moondancer     | Connected FULL speed device 'facedancer.devices.keyboard.USBKeyboardDevice' to target host.
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | rubber-ducky   | Beginning message typing demo...
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | device         | Host issued a bus reset; resetting our connection.
> INFO    | moondancer     | Target host configuration complete.
> INFO    | rubber-ducky   | Typing complete. Idly handling USB requests.
> 

After that no more working without reboot:

> sudo python rubber-ducky.py
> INFO    | moondancer     | Using the Moondancer backend.
> INFO    | moondancer     | Connected FULL speed device 'facedancer.devices.keyboard.USBKeyboardDevice' to target host.
> INFO    | rubber-ducky   | Beginning message typing demo...
> INFO    | moondancer     | Disconnecting from target host.
> Traceback (most recent call last):
>   File "/facedancer/examples/rubber-ducky.py", line 25, in <module>
>     main(device, type_letters())
>   File "/usr/local/lib/python3.10/dist-packages/facedancer/devices/__init__.py", line 41, in default_main
>     device.emulate(*coroutines)
>   File "/usr/local/lib/python3.10/dist-packages/facedancer/device.py", line 228, in emulate
>     self.run_with(*coroutines)
>   File "/usr/local/lib/python3.10/dist-packages/facedancer/device.py", line 213, in run_with
>     asyncio.run(inner())
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.10/dist-packages/facedancer/device.py", line 211, in inner
>     await asyncio.gather(self.run(), *coroutines)
>   File "/usr/local/lib/python3.10/dist-packages/facedancer/device.py", line 200, in run
>     self.backend.service_irqs()
>   File "/usr/local/lib/python3.10/dist-packages/facedancer/backends/moondancer.py", line 427, in service_irqs
>     events: List[Tuple[int, int]] = self.api.get_interrupt_events()
>   File "/usr/local/lib/python3.10/dist-packages/pygreat/comms.py", line 1126, in method
>     return self.execute_command(verb_number, in_format, out_format, name=name, class_name=class_name,
>   File "/usr/local/lib/python3.10/dist-packages/pygreat/comms.py", line 1281, in execute_command
>     return self.comms_backend.execute_command(self.CLASS_NUMBER, verb, in_format,
>   File "/usr/local/lib/python3.10/dist-packages/pygreat/comms.py", line 788, in execute_command
>     raw_result = self.execute_raw_command(class_number, verb, payload, timeout,
>   File "/usr/local/lib/python3.10/dist-packages/pygreat/comms_backends/usb1.py", line 403, in execute_raw_command
>     self.device_handle.controlWrite(usb1.TYPE_VENDOR | usb1.RECIPIENT_DEVICE,
>   File "/usr/local/lib/python3.10/dist-packages/usb1/__init__.py", line 1330, in controlWrite
>     return self._controlTransfer(request_type, request, value, index, data,
>   File "/usr/local/lib/python3.10/dist-packages/usb1/__init__.py", line 1307, in _controlTransfer
>     mayRaiseUSBError(result)
>   File "/usr/local/lib/python3.10/dist-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
>     __raiseUSBError(value)
>   File "/usr/local/lib/python3.10/dist-packages/usb1/__init__.py", line 119, in raiseUSBError
>     raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
> usb1.USBErrorTimeout: LIBUSB_ERROR_TIMEOUT [-7]
>

**Pull request merged**
