### PR TITLE
Update udev rules

### PR DESCRIPTION
**Pull request by mossmann**
- Remove legacy VID/PIDs
- Remove pid.codes test PIDs, supplied by LUNA
- Update symlink names

This eliminates overlap of the udev rules supplied by Cynthion, LUNA, and Apollo. See also:
- https://github.com/greatscottgadgets/apollo/pull/91
- https://github.com/greatscottgadgets/luna/pull/268

### CODE REVIEW

**Comment by antoinevg** [comment]
I think we should leave these alone in this repo.

My reasoning is that I don't think we should make folk who are not going to be using `cynthion` to install the udev rules go digging through other repos to figure out what all should be in there. 

A second option would be to delete the entire file & directory and instead add the contents to the documentation, but I personally prefer just leaving them as is.

**Comment by antoinevg** [comment]
This file&directory should simply be deleted and moved to the `/cynthion/python/assets/` directory as I need it in there anyway for the `cynthion` udev installation. 🙈

**Comment by mossmann** [comment]
Part of my reasoning for eliminating LUNA and Apollo udev rules is that the LUNA and Apollo rules can be added to the assets when building the package (as is to be done for Apollo firmware). We want `cynthion` to be able to install rules for those dependencies as a convenience to the user, but we don't want the rules to overlap if folks are installing them manually.

A particular case I'm concerned about is distro packaging. With something like `apt install apollo`, I would want the Apollo udev rules installed. With `apt install cynthion`, I would want the Apollo and LUNA packages brought in as dependencies, each with their own udev rules.

**Review by antoinevg — APPROVED** [review]

**Comment by mossmann** [comment]
> This file&directory should simply be deleted and moved to the `/cynthion/python/assets/` directory as I need it in there anyway for the `cynthion` udev installation. 🙈

I see you've approved, but would you like me to move the rules to `/cynthion/python/assets/` before we merge?

**Comment by antoinevg** [comment]
Ugh, yes please!

**Pull request merged**
